AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-sam-python-example

Globals:
  Function:
    Timeout: 60
    Tracing: Active
  Api:
    TracingEnabled: True

Parameters:
  Region:
    Type: String
    Default: us-east-1
  TableName:
    Type: String
    Default: ContentsTable
  EnvName:
    Type: String
    Default: "AWS" # AWS_SAM_LOCAL

Resources:
  ContentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  HelloWorldService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  NoticiaService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/noticia/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE: !Ref TableName
          AWSENV: !Ref EnvName
      Policies: AmazonDynamoDBFullAccess
      Events:
        ConsultarNoticia:
          Type: Api
          Properties:
            Path: /consultar/noticia
            Method: get
        UploadNoticia:
          Type: Api
          Properties:
            Path: /upload/noticia
            Method: post
        ListarNoticias:
          Type: Api
          Properties:
            Path: /listar/noticias
            Method: get

  NoticiaEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Regra para eventos de noticia"
      State: "ENABLED"
      EventPattern:
        source:
          - "contents.noticia"
        detail:
          state:
            - "created"
      Targets:
        - Arn: !GetAtt NoticiaService.Arn
          Id: "NoticiaServiceTarget"

  PermissionForEventsToInvokeNoticiaService:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NoticiaService
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt NoticiaEventRule.Arn

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
